name = "glearray"
version = "1.0.0"

description = "Immutable arrays for Gleam"
licences = ["Apache-2.0"]
repository = { type = "github", user = "lunagl", repo = "glearray" }
links = []

[dependencies]
gleam_stdlib = "~> 0.37"
gleam_yielder = ">= 1.1.0 and < 2.0.0"

[dev-dependencies]
gleeunit = "~> 1.1"
